### PR TITLE
Added dropdown to navbar

### PR DESCRIPTION
**Pull request by johnwheal**

### CODE REVIEW

**Comment by johnwheal** [comment]
I've had to add jQuery and bootstrap javascript to make the dropdown work. @zaccolley I'll let you figure out how to add javascript.

**Comment by zoetrope69** [comment]
Is there a way of not having JS for this feature? Seems like a static 'Sign out' button would suffice.

**Comment by johnwheal** [comment]
It would be nice to have the user's name in the top right. I was thinking we could add "My Details" before sign out. The full bootstrap js is not needed. It's only a couple of lines in jquery. Will we be using jQuery or another library for anything else?

**Comment by zoetrope69** [comment]
Ahh yeah that would be good.

Depends on what flexibility we have with Moxie maybe? Hopefully can just use jQuery aha

**Pull request merged**
